In [1]:
pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas 


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd 

In [4]:
import numpy as np 

In [5]:
pd.__version__

'2.0.2'

In [6]:
np.__version__ 

'1.24.3'

In [7]:
pip install --upgrade pandas

  Using cached pandas-2.1.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.2
    Uninstalling pandas-2.0.2:
      Successfully uninstalled pandas-2.0.2

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.1.3'

In [4]:
pip install --upgrade numpy

  Using cached numpy-1.26.2-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.3
    Uninstalling numpy-1.24.3:
      Successfully uninstalled numpy-1.24.3

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.1.3'

In [3]:
np.__version__

'1.26.2'

Numpy - n-dimensional array -> a collection of elements

In [4]:
a_py = [10, 60, 40, 199, 213, 1599]

In [5]:
type(a_py)

list

In [6]:
b_np = np.array([10, 60, 40, 199, 213, 1599])

In [7]:
b_np

array([  10,   60,   40,  199,  213, 1599])

In [8]:
type(b_np)

numpy.ndarray

In [9]:
a_py

[10, 60, 40, 199, 213, 1599]

In [10]:
b_np

array([  10,   60,   40,  199,  213, 1599])

Applying operations or Transformations to numpy arrays is much quicker.

Q1 : Multiply all the numbers in the above list by 10.

In [11]:
arr = []

for i in a_py:
    arr.append(i * 10)

arr     

[100, 600, 400, 1990, 2130, 15990]

In [12]:
# More functional approach
list(map(lambda i: i * 10, a_py))

[100, 600, 400, 1990, 2130, 15990]

In [13]:
# List Comphrehensiona approach
[i * 10 for i in a_py]

[100, 600, 400, 1990, 2130, 15990]

In [14]:
b_np * 10

array([  100,   600,   400,  1990,  2130, 15990])

# simple array of integers

In [15]:
c_np = np.array([1, 2, 3])

In [16]:
c_np.dtype

dtype('int64')

In [17]:
c_np = np.array([1, 2.0, 3])

In [18]:
c_np

array([1., 2., 3.])

In [19]:
c_np.dtype

dtype('float64')

In [20]:
[1, 2.0, 3, 'Anup', {'bootcamp' : 'pandas'}]

[1, 2.0, 3, 'Anup', {'bootcamp': 'pandas'}]